### ISSUE TITLE
MonadThese?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-these#6]
Also known as `MonadChronicle` in [these](https://hackage.haskell.org/package/these).

**Comment by garyb** [comment]
Wow, the members of `MonadChronicle` have horrible names :wink:

I prefer `MonadThese` too.

**Comment by puffnfresh** [comment]
Interesting, I like it :+1:

**Comment by thomashoneyman** [comment]
I'm closing this due to a lack of response over the last several years, but please feel free to re-open if it ought to be revisited.
